language: node_js

node_js:
  - 10

script:
  - echo 👌

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: public/
  target-branch: master
  on:
    branch: develop
