language: "javascript"
node_js:
 - "0.10"
install:
 - sudo apt-get install rubygems nodejs
 - sudo gem install sass
 - sudo npm install -g gulp bower
 - npm install
 - bower install
script:
 - gulp build
branches:
 only:
  - main
