language: node_js
node_js:
 - "0.10"
before_install:
 - sudo apt-get install rubygems
 - sudo gem install sass
 - npm install -g gulp bower
install:
 - npm install
 - bower install
script:
 - gulp build
branches:
 only:
  - main
  - travisFix
