language: "javascript"
rvm:
 - "1.8.7"
node_js:
 - "0.10"
install:
 - sudo gem install sass
 - npm install -g gulp bower
 - npm install
 - bower install
script:
 - gulp build
branches:
 only:
  - main
