source_url: 'https://github.com/p2kmgcl/p2kmgcl.github.com/'
url:        'http://www.pablomolina.me'
baseurl:    '' # Example: '/subfolder'
permalink:  '/:title/index.html'

exclude:
    - Gemfile
    - LICENSE.md
    - README.md
    - .c9
    - .git
    - .sass-cache

markdown: 'redcarpet'
sass:
    style: 'compressed'
