languages:
  - id: 'es'
    name: 'Español'
  - id: 'en'
    name: 'English'

###############################################################################
es:
  title:          'Pablo Molina'
  subtitle:       'Piensa, inventa, comparte'
  description:    'Web personal de Pablo Molina.'
  keywords:       'diseño web, programación, internet, web personal, pablo molina, perfil, jekyll'

  home:           'Inicio'
  mainmenu:       'Menú principal'
  pages:          'Páginas'
  themes:         'Temas'
  languages:      'Idiomas'

  license:
    sumUp:      'Todo esto es tuyo, tan sólo recuerda mi nombre'
    project:    'Web personal de Pablo Molina'
    by:         'por'
    under:      'se encuentra bajo una'
    name:       'Licencia Creative Commons Atribución 3.0 Unported'
    based:      'Basada en una obra en'
    permisions: 'Permisos que vayan más allá de lo cubierto por esta licencia pueden encontrarse en'
#!#############################################################################

###############################################################################
en:
  title:          'Pablo Molina'
  subtitle:       'Think, invent, share'
  description:    "Pablo Molina's personal website."
  keywords:       'web design, programming, internet, personal website, pablo molina, profile, jekyll'

  home:           'Home'
  mainmenu:       'Main menu'
  pages:          'Pages'
  themes:         'Themes'
  languages:      'Languages'

  license:
    sumUp:      "This is all yours, just remember my name"
    project:    "Pablo Molina's personal website"
    by:         'by'
    under:      'is licensed under a'
    name:       'Creative Commons Atribución 3.0 Unported License'
    based:      'Based on work at'
    permisions: 'Permissions beyond the scope of this license may be available at'
#!#############################################################################

baseurl:    "http://www.pablomolina.me"

theme:
  main: "loremipsum"
  less: "_includes/themes"
  css:  "css"
  list:
    - id: "loremipsum"
      name: "Lorem Ipsum"
