[build]
  base = "."
  publish = "build/app/"
  command = "npm run build"

[[redirects]]
  from = "/generated/styles/theme.css"
  to = "/generated/styles/theme-comic.css"
  force = true
  conditions = {Cookie = ["site_theme_comic"]}

[[redirects]]
  from = "/generated/styles/theme.css"
  to = "/generated/styles/theme-simplicity.css"
  force = true
  conditions = {Cookie = ["site_theme_simplicity"]}

[[redirects]]
  from = "/generated/styles/theme.css"
  to = "/generated/styles/theme-coolgra.css"
  force = true
  conditions = {Cookie = ["site_theme_coolgra"]}

[[redirects]]
  from = "/generated/styles/theme.css"
  to = "/generated/styles/theme-simplicity.css"
  force = true

[[redirects]]
  from = "/r/liferay-fragments"
  to = "https://github.com/p2kmgcl/testing-fragments/blob/master/docs/react-fragments-and-widgets-slides.pdf"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8.8.0"

[dev]
  framework = "#custom"
  command = "astro dev"
  targetPort = 3000
  autoLaunch = false
