[build]
  base = "."
  publish = "build/app/"
  command = "yarn run build"

[dev]
  framework = "#custom"
  command = "yarn run start:next"
  targetPort = 3000

[[headers]]
  for = "/gists/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
