title: Pablo Molina
description: Pablo Molina's website with links to his social network profiles, contact information and projects
url: https://pablomolina.me
baseurl: /
themeColor: "#444"
favicons: [32, 192, 512]

collections:
  pages:
    output: true
    permalink: :title

defaults:
  - scope:
      path: ''
    values:
      layout: 'page'

sass:
  style: compressed
